stages:
    - build
    - test
build:
    stage: build
    script: 
        - echo "build stage"
        - mkdir build
        - touch build/info.txt
    tags:
        - personal
test:
    stage: test
    script:
        - echo "test stage"
